GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO <yourusername>;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO <yourusername>;
GRANT CONNECT ON DATABASE <myapp> TO <yourusername>;
